// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.hypers.www.protocolbufferdemo.nano;

@SuppressWarnings("hiding")
public interface HMT {

  public static final class HMA extends
      com.google.protobuf.nano.MessageNano {

    private static volatile HMA[] _emptyArray;
    public static HMA[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new HMA[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .HmtObjBase base = 1;
    public HmtObjBase[] base;

    // repeated .HmtObjMMA mma = 2;
    public HmtObjMMA[] mma;

    // repeated .HmtObjActivity activity_list = 3;
    public HmtObjActivity[] activityList;

    // repeated .HmtObjAct act_list = 4;
    public HmtObjAct[] actList;

    // repeated .HmtObjError error_list = 5;
    public HmtObjError[] errorList;

    // repeated .HmtObjClientData client_data_list = 6;
    public HmtObjClientData[] clientDataList;

    public HMA() {
      clear();
    }

    public HMA clear() {
      base = HmtObjBase.emptyArray();
      mma = HmtObjMMA.emptyArray();
      activityList = HmtObjActivity.emptyArray();
      actList = HmtObjAct.emptyArray();
      errorList = HmtObjError.emptyArray();
      clientDataList = HmtObjClientData.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.base != null && this.base.length > 0) {
        for (int i = 0; i < this.base.length; i++) {
          HmtObjBase element = this.base[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      if (this.mma != null && this.mma.length > 0) {
        for (int i = 0; i < this.mma.length; i++) {
          HmtObjMMA element = this.mma[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (this.activityList != null && this.activityList.length > 0) {
        for (int i = 0; i < this.activityList.length; i++) {
          HmtObjActivity element = this.activityList[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      if (this.actList != null && this.actList.length > 0) {
        for (int i = 0; i < this.actList.length; i++) {
          HmtObjAct element = this.actList[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      if (this.errorList != null && this.errorList.length > 0) {
        for (int i = 0; i < this.errorList.length; i++) {
          HmtObjError element = this.errorList[i];
          if (element != null) {
            output.writeMessage(5, element);
          }
        }
      }
      if (this.clientDataList != null && this.clientDataList.length > 0) {
        for (int i = 0; i < this.clientDataList.length; i++) {
          HmtObjClientData element = this.clientDataList[i];
          if (element != null) {
            output.writeMessage(6, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.base != null && this.base.length > 0) {
        for (int i = 0; i < this.base.length; i++) {
          HmtObjBase element = this.base[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      if (this.mma != null && this.mma.length > 0) {
        for (int i = 0; i < this.mma.length; i++) {
          HmtObjMMA element = this.mma[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (this.activityList != null && this.activityList.length > 0) {
        for (int i = 0; i < this.activityList.length; i++) {
          HmtObjActivity element = this.activityList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      if (this.actList != null && this.actList.length > 0) {
        for (int i = 0; i < this.actList.length; i++) {
          HmtObjAct element = this.actList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      if (this.errorList != null && this.errorList.length > 0) {
        for (int i = 0; i < this.errorList.length; i++) {
          HmtObjError element = this.errorList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(5, element);
          }
        }
      }
      if (this.clientDataList != null && this.clientDataList.length > 0) {
        for (int i = 0; i < this.clientDataList.length; i++) {
          HmtObjClientData element = this.clientDataList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(6, element);
          }
        }
      }
      return size;
    }

    @Override
    public HMA mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.base == null ? 0 : this.base.length;
            HmtObjBase[] newArray =
                new HmtObjBase[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.base, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new HmtObjBase();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new HmtObjBase();
            input.readMessage(newArray[i]);
            this.base = newArray;
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.mma == null ? 0 : this.mma.length;
            HmtObjMMA[] newArray =
                new HmtObjMMA[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.mma, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new HmtObjMMA();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new HmtObjMMA();
            input.readMessage(newArray[i]);
            this.mma = newArray;
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.activityList == null ? 0 : this.activityList.length;
            HmtObjActivity[] newArray =
                new HmtObjActivity[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.activityList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new HmtObjActivity();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new HmtObjActivity();
            input.readMessage(newArray[i]);
            this.activityList = newArray;
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.actList == null ? 0 : this.actList.length;
            HmtObjAct[] newArray =
                new HmtObjAct[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.actList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new HmtObjAct();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new HmtObjAct();
            input.readMessage(newArray[i]);
            this.actList = newArray;
            break;
          }
          case 42: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 42);
            int i = this.errorList == null ? 0 : this.errorList.length;
            HmtObjError[] newArray =
                new HmtObjError[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.errorList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new HmtObjError();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new HmtObjError();
            input.readMessage(newArray[i]);
            this.errorList = newArray;
            break;
          }
          case 50: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 50);
            int i = this.clientDataList == null ? 0 : this.clientDataList.length;
            HmtObjClientData[] newArray =
                new HmtObjClientData[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.clientDataList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new HmtObjClientData();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new HmtObjClientData();
            input.readMessage(newArray[i]);
            this.clientDataList = newArray;
            break;
          }
        }
      }
    }

    public static HMA parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new HMA(), data);
    }

    public static HMA parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new HMA().mergeFrom(input);
    }
  }

  public static final class HmtObjBase extends
      com.google.protobuf.nano.MessageNano {

    private static volatile HmtObjBase[] _emptyArray;
    public static HmtObjBase[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new HmtObjBase[0];
          }
        }
      }
      return _emptyArray;
    }

    // string ts = 1;
    public String ts;

    // string v = 2;
    public String v;

    // string sv = 3;
    public String sv;

    // string sr = 4;
    public String sr;

    // string sd = 5;
    public String sd;

    // string lang = 6;
    public String lang;

    // string char = 7;
    public String char_;

    // string muid = 8;
    public String muid;

    // string uid = 9;
    public String uid;

    // string encrypt = 10;
    public String encrypt;

    // string _ua = 11;
    public String Ua;

    // string channel_id = 12;
    public String channelId;

    // string type = 13;
    public String type;

    public HmtObjBase() {
      clear();
    }

    public HmtObjBase clear() {
      ts = "";
      v = "";
      sv = "";
      sr = "";
      sd = "";
      lang = "";
      char_ = "";
      muid = "";
      uid = "";
      encrypt = "";
      Ua = "";
      channelId = "";
      type = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.ts.equals("")) {
        output.writeString(1, this.ts);
      }
      if (!this.v.equals("")) {
        output.writeString(2, this.v);
      }
      if (!this.sv.equals("")) {
        output.writeString(3, this.sv);
      }
      if (!this.sr.equals("")) {
        output.writeString(4, this.sr);
      }
      if (!this.sd.equals("")) {
        output.writeString(5, this.sd);
      }
      if (!this.lang.equals("")) {
        output.writeString(6, this.lang);
      }
      if (!this.char_.equals("")) {
        output.writeString(7, this.char_);
      }
      if (!this.muid.equals("")) {
        output.writeString(8, this.muid);
      }
      if (!this.uid.equals("")) {
        output.writeString(9, this.uid);
      }
      if (!this.encrypt.equals("")) {
        output.writeString(10, this.encrypt);
      }
      if (!this.Ua.equals("")) {
        output.writeString(11, this.Ua);
      }
      if (!this.channelId.equals("")) {
        output.writeString(12, this.channelId);
      }
      if (!this.type.equals("")) {
        output.writeString(13, this.type);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.ts.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.ts);
      }
      if (!this.v.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.v);
      }
      if (!this.sv.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.sv);
      }
      if (!this.sr.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.sr);
      }
      if (!this.sd.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.sd);
      }
      if (!this.lang.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.lang);
      }
      if (!this.char_.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.char_);
      }
      if (!this.muid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.muid);
      }
      if (!this.uid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.uid);
      }
      if (!this.encrypt.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(10, this.encrypt);
      }
      if (!this.Ua.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(11, this.Ua);
      }
      if (!this.channelId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(12, this.channelId);
      }
      if (!this.type.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(13, this.type);
      }
      return size;
    }

    @Override
    public HmtObjBase mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.ts = input.readString();
            break;
          }
          case 18: {
            this.v = input.readString();
            break;
          }
          case 26: {
            this.sv = input.readString();
            break;
          }
          case 34: {
            this.sr = input.readString();
            break;
          }
          case 42: {
            this.sd = input.readString();
            break;
          }
          case 50: {
            this.lang = input.readString();
            break;
          }
          case 58: {
            this.char_ = input.readString();
            break;
          }
          case 66: {
            this.muid = input.readString();
            break;
          }
          case 74: {
            this.uid = input.readString();
            break;
          }
          case 82: {
            this.encrypt = input.readString();
            break;
          }
          case 90: {
            this.Ua = input.readString();
            break;
          }
          case 98: {
            this.channelId = input.readString();
            break;
          }
          case 106: {
            this.type = input.readString();
            break;
          }
        }
      }
    }

    public static HmtObjBase parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new HmtObjBase(), data);
    }

    public static HmtObjBase parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new HmtObjBase().mergeFrom(input);
    }
  }

  public static final class HmtObjMMA extends
      com.google.protobuf.nano.MessageNano {

    private static volatile HmtObjMMA[] _emptyArray;
    public static HmtObjMMA[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new HmtObjMMA[0];
          }
        }
      }
      return _emptyArray;
    }

    // string _z = 1;
    public String Z;

    // string os = 2;
    public String os;

    // string idfa = 3;
    public String idfa;

    // string idfv = 4;
    public String idfv;

    // string openudid = 5;
    public String openudid;

    // string mac = 6;
    public String mac;

    // string mac1 = 7;
    public String mac1;

    // string os_version = 8;
    public String osVersion;

    // string app_name = 9;
    public String appName;

    // string app_version = 10;
    public String appVersion;

    // string app_code = 11;
    public String appCode;

    // string device_id = 12;
    public String deviceId;

    // string device_name = 13;
    public String deviceName;

    // string useragent = 14;
    public String useragent;

    public HmtObjMMA() {
      clear();
    }

    public HmtObjMMA clear() {
      Z = "";
      os = "";
      idfa = "";
      idfv = "";
      openudid = "";
      mac = "";
      mac1 = "";
      osVersion = "";
      appName = "";
      appVersion = "";
      appCode = "";
      deviceId = "";
      deviceName = "";
      useragent = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.Z.equals("")) {
        output.writeString(1, this.Z);
      }
      if (!this.os.equals("")) {
        output.writeString(2, this.os);
      }
      if (!this.idfa.equals("")) {
        output.writeString(3, this.idfa);
      }
      if (!this.idfv.equals("")) {
        output.writeString(4, this.idfv);
      }
      if (!this.openudid.equals("")) {
        output.writeString(5, this.openudid);
      }
      if (!this.mac.equals("")) {
        output.writeString(6, this.mac);
      }
      if (!this.mac1.equals("")) {
        output.writeString(7, this.mac1);
      }
      if (!this.osVersion.equals("")) {
        output.writeString(8, this.osVersion);
      }
      if (!this.appName.equals("")) {
        output.writeString(9, this.appName);
      }
      if (!this.appVersion.equals("")) {
        output.writeString(10, this.appVersion);
      }
      if (!this.appCode.equals("")) {
        output.writeString(11, this.appCode);
      }
      if (!this.deviceId.equals("")) {
        output.writeString(12, this.deviceId);
      }
      if (!this.deviceName.equals("")) {
        output.writeString(13, this.deviceName);
      }
      if (!this.useragent.equals("")) {
        output.writeString(14, this.useragent);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.Z.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.Z);
      }
      if (!this.os.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.os);
      }
      if (!this.idfa.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.idfa);
      }
      if (!this.idfv.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.idfv);
      }
      if (!this.openudid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.openudid);
      }
      if (!this.mac.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.mac);
      }
      if (!this.mac1.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.mac1);
      }
      if (!this.osVersion.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.osVersion);
      }
      if (!this.appName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.appName);
      }
      if (!this.appVersion.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(10, this.appVersion);
      }
      if (!this.appCode.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(11, this.appCode);
      }
      if (!this.deviceId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(12, this.deviceId);
      }
      if (!this.deviceName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(13, this.deviceName);
      }
      if (!this.useragent.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(14, this.useragent);
      }
      return size;
    }

    @Override
    public HmtObjMMA mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.Z = input.readString();
            break;
          }
          case 18: {
            this.os = input.readString();
            break;
          }
          case 26: {
            this.idfa = input.readString();
            break;
          }
          case 34: {
            this.idfv = input.readString();
            break;
          }
          case 42: {
            this.openudid = input.readString();
            break;
          }
          case 50: {
            this.mac = input.readString();
            break;
          }
          case 58: {
            this.mac1 = input.readString();
            break;
          }
          case 66: {
            this.osVersion = input.readString();
            break;
          }
          case 74: {
            this.appName = input.readString();
            break;
          }
          case 82: {
            this.appVersion = input.readString();
            break;
          }
          case 90: {
            this.appCode = input.readString();
            break;
          }
          case 98: {
            this.deviceId = input.readString();
            break;
          }
          case 106: {
            this.deviceName = input.readString();
            break;
          }
          case 114: {
            this.useragent = input.readString();
            break;
          }
        }
      }
    }

    public static HmtObjMMA parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new HmtObjMMA(), data);
    }

    public static HmtObjMMA parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new HmtObjMMA().mergeFrom(input);
    }
  }

  public static final class HmtObjActivity extends
      com.google.protobuf.nano.MessageNano {

    private static volatile HmtObjActivity[] _emptyArray;
    public static HmtObjActivity[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new HmtObjActivity[0];
          }
        }
      }
      return _emptyArray;
    }

    // string session_id = 1;
    public String sessionId;

    // string start_ts = 2;
    public String startTs;

    // string end_ts = 3;
    public String endTs;

    // string duration = 4;
    public String duration;

    // string activity = 5;
    public String activity;

    // string original_activity = 6;
    public String originalActivity;

    public HmtObjActivity() {
      clear();
    }

    public HmtObjActivity clear() {
      sessionId = "";
      startTs = "";
      endTs = "";
      duration = "";
      activity = "";
      originalActivity = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.sessionId.equals("")) {
        output.writeString(1, this.sessionId);
      }
      if (!this.startTs.equals("")) {
        output.writeString(2, this.startTs);
      }
      if (!this.endTs.equals("")) {
        output.writeString(3, this.endTs);
      }
      if (!this.duration.equals("")) {
        output.writeString(4, this.duration);
      }
      if (!this.activity.equals("")) {
        output.writeString(5, this.activity);
      }
      if (!this.originalActivity.equals("")) {
        output.writeString(6, this.originalActivity);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.sessionId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.sessionId);
      }
      if (!this.startTs.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.startTs);
      }
      if (!this.endTs.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.endTs);
      }
      if (!this.duration.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.duration);
      }
      if (!this.activity.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.activity);
      }
      if (!this.originalActivity.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.originalActivity);
      }
      return size;
    }

    @Override
    public HmtObjActivity mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.sessionId = input.readString();
            break;
          }
          case 18: {
            this.startTs = input.readString();
            break;
          }
          case 26: {
            this.endTs = input.readString();
            break;
          }
          case 34: {
            this.duration = input.readString();
            break;
          }
          case 42: {
            this.activity = input.readString();
            break;
          }
          case 50: {
            this.originalActivity = input.readString();
            break;
          }
        }
      }
    }

    public static HmtObjActivity parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new HmtObjActivity(), data);
    }

    public static HmtObjActivity parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new HmtObjActivity().mergeFrom(input);
    }
  }

  public static final class HmtObjAct extends
      com.google.protobuf.nano.MessageNano {

    private static volatile HmtObjAct[] _emptyArray;
    public static HmtObjAct[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new HmtObjAct[0];
          }
        }
      }
      return _emptyArray;
    }

    // string act_name = 1;
    public String actName;

    // string act_count = 2;
    public String actCount;

    // string activity = 3;
    public String activity;

    public HmtObjAct() {
      clear();
    }

    public HmtObjAct clear() {
      actName = "";
      actCount = "";
      activity = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.actName.equals("")) {
        output.writeString(1, this.actName);
      }
      if (!this.actCount.equals("")) {
        output.writeString(2, this.actCount);
      }
      if (!this.activity.equals("")) {
        output.writeString(3, this.activity);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.actName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.actName);
      }
      if (!this.actCount.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.actCount);
      }
      if (!this.activity.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.activity);
      }
      return size;
    }

    @Override
    public HmtObjAct mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.actName = input.readString();
            break;
          }
          case 18: {
            this.actCount = input.readString();
            break;
          }
          case 26: {
            this.activity = input.readString();
            break;
          }
        }
      }
    }

    public static HmtObjAct parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new HmtObjAct(), data);
    }

    public static HmtObjAct parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new HmtObjAct().mergeFrom(input);
    }
  }

  public static final class HmtObjError extends
      com.google.protobuf.nano.MessageNano {

    private static volatile HmtObjError[] _emptyArray;
    public static HmtObjError[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new HmtObjError[0];
          }
        }
      }
      return _emptyArray;
    }

    // string stack_trace = 1;
    public String stackTrace;

    // string activity = 2;
    public String activity;

    public HmtObjError() {
      clear();
    }

    public HmtObjError clear() {
      stackTrace = "";
      activity = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.stackTrace.equals("")) {
        output.writeString(1, this.stackTrace);
      }
      if (!this.activity.equals("")) {
        output.writeString(2, this.activity);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.stackTrace.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.stackTrace);
      }
      if (!this.activity.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.activity);
      }
      return size;
    }

    @Override
    public HmtObjError mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.stackTrace = input.readString();
            break;
          }
          case 18: {
            this.activity = input.readString();
            break;
          }
        }
      }
    }

    public static HmtObjError parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new HmtObjError(), data);
    }

    public static HmtObjError parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new HmtObjError().mergeFrom(input);
    }
  }

  public static final class HmtObjClientData extends
      com.google.protobuf.nano.MessageNano {

    private static volatile HmtObjClientData[] _emptyArray;
    public static HmtObjClientData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new HmtObjClientData[0];
          }
        }
      }
      return _emptyArray;
    }

    // string _idfa = 1;
    public String Idfa;

    // string _imei = 2;
    public String Imei;

    // string _openudid = 3;
    public String Openudid;

    // string _duid = 4;
    public String Duid;

    // string _androidid = 5;
    public String Androidid;

    // string _mac = 6;
    public String Mac;

    // string cell_id = 7;
    public String cellId;

    // bool is_mobile_device = 8;
    public boolean isMobileDevice;

    // bool have_wifi = 9;
    public boolean haveWifi;

    // string lac = 10;
    public String lac;

    // string network = 11;
    public String network;

    // bool have_bt = 12;
    public boolean haveBt;

    // string phone_type = 13;
    public String phoneType;

    // bool have_gps = 14;
    public boolean haveGps;

    // string model = 15;
    public String model;

    // string manufacturer = 16;
    public String manufacturer;

    // string producer = 17;
    public String producer;

    // string mccmnc = 18;
    public String mccmnc;

    // string lon = 19;
    public String lon;

    // string lat = 20;
    public String lat;

    // string imsi = 21;
    public String imsi;

    // bool have_gravity = 22;
    public boolean haveGravity;

    // bool is_jail_break = 23;
    public boolean isJailBreak;

    // string package_name = 24;
    public String packageName;

    public HmtObjClientData() {
      clear();
    }

    public HmtObjClientData clear() {
      Idfa = "";
      Imei = "";
      Openudid = "";
      Duid = "";
      Androidid = "";
      Mac = "";
      cellId = "";
      isMobileDevice = false;
      haveWifi = false;
      lac = "";
      network = "";
      haveBt = false;
      phoneType = "";
      haveGps = false;
      model = "";
      manufacturer = "";
      producer = "";
      mccmnc = "";
      lon = "";
      lat = "";
      imsi = "";
      haveGravity = false;
      isJailBreak = false;
      packageName = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.Idfa.equals("")) {
        output.writeString(1, this.Idfa);
      }
      if (!this.Imei.equals("")) {
        output.writeString(2, this.Imei);
      }
      if (!this.Openudid.equals("")) {
        output.writeString(3, this.Openudid);
      }
      if (!this.Duid.equals("")) {
        output.writeString(4, this.Duid);
      }
      if (!this.Androidid.equals("")) {
        output.writeString(5, this.Androidid);
      }
      if (!this.Mac.equals("")) {
        output.writeString(6, this.Mac);
      }
      if (!this.cellId.equals("")) {
        output.writeString(7, this.cellId);
      }
      if (this.isMobileDevice != false) {
        output.writeBool(8, this.isMobileDevice);
      }
      if (this.haveWifi != false) {
        output.writeBool(9, this.haveWifi);
      }
      if (!this.lac.equals("")) {
        output.writeString(10, this.lac);
      }
      if (!this.network.equals("")) {
        output.writeString(11, this.network);
      }
      if (this.haveBt != false) {
        output.writeBool(12, this.haveBt);
      }
      if (!this.phoneType.equals("")) {
        output.writeString(13, this.phoneType);
      }
      if (this.haveGps != false) {
        output.writeBool(14, this.haveGps);
      }
      if (!this.model.equals("")) {
        output.writeString(15, this.model);
      }
      if (!this.manufacturer.equals("")) {
        output.writeString(16, this.manufacturer);
      }
      if (!this.producer.equals("")) {
        output.writeString(17, this.producer);
      }
      if (!this.mccmnc.equals("")) {
        output.writeString(18, this.mccmnc);
      }
      if (!this.lon.equals("")) {
        output.writeString(19, this.lon);
      }
      if (!this.lat.equals("")) {
        output.writeString(20, this.lat);
      }
      if (!this.imsi.equals("")) {
        output.writeString(21, this.imsi);
      }
      if (this.haveGravity != false) {
        output.writeBool(22, this.haveGravity);
      }
      if (this.isJailBreak != false) {
        output.writeBool(23, this.isJailBreak);
      }
      if (!this.packageName.equals("")) {
        output.writeString(24, this.packageName);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.Idfa.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.Idfa);
      }
      if (!this.Imei.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.Imei);
      }
      if (!this.Openudid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.Openudid);
      }
      if (!this.Duid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.Duid);
      }
      if (!this.Androidid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.Androidid);
      }
      if (!this.Mac.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.Mac);
      }
      if (!this.cellId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.cellId);
      }
      if (this.isMobileDevice != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(8, this.isMobileDevice);
      }
      if (this.haveWifi != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(9, this.haveWifi);
      }
      if (!this.lac.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(10, this.lac);
      }
      if (!this.network.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(11, this.network);
      }
      if (this.haveBt != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(12, this.haveBt);
      }
      if (!this.phoneType.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(13, this.phoneType);
      }
      if (this.haveGps != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(14, this.haveGps);
      }
      if (!this.model.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(15, this.model);
      }
      if (!this.manufacturer.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(16, this.manufacturer);
      }
      if (!this.producer.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(17, this.producer);
      }
      if (!this.mccmnc.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(18, this.mccmnc);
      }
      if (!this.lon.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(19, this.lon);
      }
      if (!this.lat.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(20, this.lat);
      }
      if (!this.imsi.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(21, this.imsi);
      }
      if (this.haveGravity != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(22, this.haveGravity);
      }
      if (this.isJailBreak != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(23, this.isJailBreak);
      }
      if (!this.packageName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(24, this.packageName);
      }
      return size;
    }

    @Override
    public HmtObjClientData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.Idfa = input.readString();
            break;
          }
          case 18: {
            this.Imei = input.readString();
            break;
          }
          case 26: {
            this.Openudid = input.readString();
            break;
          }
          case 34: {
            this.Duid = input.readString();
            break;
          }
          case 42: {
            this.Androidid = input.readString();
            break;
          }
          case 50: {
            this.Mac = input.readString();
            break;
          }
          case 58: {
            this.cellId = input.readString();
            break;
          }
          case 64: {
            this.isMobileDevice = input.readBool();
            break;
          }
          case 72: {
            this.haveWifi = input.readBool();
            break;
          }
          case 82: {
            this.lac = input.readString();
            break;
          }
          case 90: {
            this.network = input.readString();
            break;
          }
          case 96: {
            this.haveBt = input.readBool();
            break;
          }
          case 106: {
            this.phoneType = input.readString();
            break;
          }
          case 112: {
            this.haveGps = input.readBool();
            break;
          }
          case 122: {
            this.model = input.readString();
            break;
          }
          case 130: {
            this.manufacturer = input.readString();
            break;
          }
          case 138: {
            this.producer = input.readString();
            break;
          }
          case 146: {
            this.mccmnc = input.readString();
            break;
          }
          case 154: {
            this.lon = input.readString();
            break;
          }
          case 162: {
            this.lat = input.readString();
            break;
          }
          case 170: {
            this.imsi = input.readString();
            break;
          }
          case 176: {
            this.haveGravity = input.readBool();
            break;
          }
          case 184: {
            this.isJailBreak = input.readBool();
            break;
          }
          case 194: {
            this.packageName = input.readString();
            break;
          }
        }
      }
    }

    public static HmtObjClientData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new HmtObjClientData(), data);
    }

    public static HmtObjClientData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new HmtObjClientData().mergeFrom(input);
    }
  }
}
