// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.hypers.www.protocolbufferdemo;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>string email = 3;</code>
     */
    String getEmail();
    /**
     * <code>string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    java.util.List<Person.PhoneNumber>
        getPhonesList();
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    Person.PhoneNumber getPhones(int index);
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    int getPhonesCount();
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageLite<
          Person, Person.Builder> implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    private Person() {
      name_ = "";
      email_ = "";
      phones_ = emptyProtobufList();
    }
    /**
     * Protobuf enum {@code Person.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Person.PhoneType)
    }

    public interface PhoneNumberOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Person.PhoneNumber)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>string number = 1;</code>
       */
      String getNumber();
      /**
       * <code>string number = 1;</code>
       */
      com.google.protobuf.ByteString
          getNumberBytes();

      /**
       * <code>.Person.PhoneType type = 2;</code>
       */
      int getTypeValue();
      /**
       * <code>.Person.PhoneType type = 2;</code>
       */
      PhoneType getType();
    }
    /**
     * Protobuf type {@code Person.PhoneNumber}
     */
    public  static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessageLite<
            PhoneNumber, PhoneNumber.Builder> implements
        // @@protoc_insertion_point(message_implements:Person.PhoneNumber)
        PhoneNumberOrBuilder {
      private PhoneNumber() {
        number_ = "";
      }
      public static final int NUMBER_FIELD_NUMBER = 1;
      private String number_;
      /**
       * <code>string number = 1;</code>
       */
      public String getNumber() {
        return number_;
      }
      /**
       * <code>string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(number_);
      }
      /**
       * <code>string number = 1;</code>
       */
      private void setNumber(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        number_ = value;
      }
      /**
       * <code>string number = 1;</code>
       */
      private void clearNumber() {
        
        number_ = getDefaultInstance().getNumber();
      }
      /**
       * <code>string number = 1;</code>
       */
      private void setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        number_ = value.toStringUtf8();
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private int type_;
      /**
       * <code>.Person.PhoneType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.Person.PhoneType type = 2;</code>
       */
      public PhoneType getType() {
        PhoneType result = PhoneType.forNumber(type_);
        return result == null ? PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Person.PhoneType type = 2;</code>
       */
      private void setTypeValue(int value) {
          type_ = value;
      }
      /**
       * <code>.Person.PhoneType type = 2;</code>
       */
      private void setType(PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
      }
      /**
       * <code>.Person.PhoneType type = 2;</code>
       */
      private void clearType() {
        
        type_ = 0;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!number_.isEmpty()) {
          output.writeString(1, getNumber());
        }
        if (type_ != PhoneType.MOBILE.getNumber()) {
          output.writeEnum(2, type_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (!number_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getNumber());
        }
        if (type_ != PhoneType.MOBILE.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_);
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(PhoneNumber prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code Person.PhoneNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            PhoneNumber, Builder> implements
          // @@protoc_insertion_point(builder_implements:Person.PhoneNumber)
          PhoneNumberOrBuilder {
        // Construct using com.hypers.www.protocolbufferdemo.AddressBookProtos.Person.PhoneNumber.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>string number = 1;</code>
         */
        public String getNumber() {
          return instance.getNumber();
        }
        /**
         * <code>string number = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          return instance.getNumberBytes();
        }
        /**
         * <code>string number = 1;</code>
         */
        public Builder setNumber(
            String value) {
          copyOnWrite();
          instance.setNumber(value);
          return this;
        }
        /**
         * <code>string number = 1;</code>
         */
        public Builder clearNumber() {
          copyOnWrite();
          instance.clearNumber();
          return this;
        }
        /**
         * <code>string number = 1;</code>
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setNumberBytes(value);
          return this;
        }

        /**
         * <code>.Person.PhoneType type = 2;</code>
         */
        public int getTypeValue() {
          return instance.getTypeValue();
        }
        /**
         * <code>.Person.PhoneType type = 2;</code>
         */
        public Builder setTypeValue(int value) {
          copyOnWrite();
          instance.setTypeValue(value);
          return this;
        }
        /**
         * <code>.Person.PhoneType type = 2;</code>
         */
        public PhoneType getType() {
          return instance.getType();
        }
        /**
         * <code>.Person.PhoneType type = 2;</code>
         */
        public Builder setType(PhoneType value) {
          copyOnWrite();
          instance.setType(value);
          return this;
        }
        /**
         * <code>.Person.PhoneType type = 2;</code>
         */
        public Builder clearType() {
          copyOnWrite();
          instance.clearType();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Person.PhoneNumber)
      }
      protected final Object dynamicMethod(
          MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new PhoneNumber();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            PhoneNumber other = (PhoneNumber) arg1;
            number_ = visitor.visitString(!number_.isEmpty(), number_,
                !other.number_.isEmpty(), other.number_);
            type_ = visitor.visitInt(type_ != 0, type_,    other.type_ != 0, other.type_);
            if (visitor == MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    String s = input.readStringRequireUtf8();

                    number_ = s;
                    break;
                  }
                  case 16: {
                    int rawValue = input.readEnum();

                    type_ = rawValue;
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (PhoneNumber.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:Person.PhoneNumber)
      private static final PhoneNumber DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new PhoneNumber();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static PhoneNumber getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<PhoneNumber> PARSER;

      public static com.google.protobuf.Parser<PhoneNumber> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private String name_;
    /**
     * <code>string name = 1;</code>
     */
    public String getName() {
      return name_;
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 1;</code>
     */
    private void setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <code>string name = 1;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 1;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>int32 id = 2;</code>
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>int32 id = 2;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private String email_;
    /**
     * <code>string email = 3;</code>
     */
    public String getEmail() {
      return email_;
    }
    /**
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>string email = 3;</code>
     */
    private void setEmail(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
    }
    /**
     * <code>string email = 3;</code>
     */
    private void clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>string email = 3;</code>
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value.toStringUtf8();
    }

    public static final int PHONES_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<PhoneNumber> phones_;
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    public java.util.List<PhoneNumber> getPhonesList() {
      return phones_;
    }
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    public java.util.List<? extends PhoneNumberOrBuilder>
        getPhonesOrBuilderList() {
      return phones_;
    }
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    public PhoneNumber getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    public PhoneNumberOrBuilder getPhonesOrBuilder(
        int index) {
      return phones_.get(index);
    }
    private void ensurePhonesIsMutable() {
      if (!phones_.isModifiable()) {
        phones_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(phones_);
       }
    }

    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    private void setPhones(
        int index, PhoneNumber value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePhonesIsMutable();
      phones_.set(index, value);
    }
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    private void setPhones(
        int index, PhoneNumber.Builder builderForValue) {
      ensurePhonesIsMutable();
      phones_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    private void addPhones(PhoneNumber value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePhonesIsMutable();
      phones_.add(value);
    }
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    private void addPhones(
        int index, PhoneNumber value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePhonesIsMutable();
      phones_.add(index, value);
    }
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    private void addPhones(
        PhoneNumber.Builder builderForValue) {
      ensurePhonesIsMutable();
      phones_.add(builderForValue.build());
    }
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    private void addPhones(
        int index, PhoneNumber.Builder builderForValue) {
      ensurePhonesIsMutable();
      phones_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    private void addAllPhones(
        Iterable<? extends PhoneNumber> values) {
      ensurePhonesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, phones_);
    }
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    private void clearPhones() {
      phones_ = emptyProtobufList();
    }
    /**
     * <code>repeated .Person.PhoneNumber phones = 4;</code>
     */
    private void removePhones(int index) {
      ensurePhonesIsMutable();
      phones_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!name_.isEmpty()) {
        output.writeString(1, getName());
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      if (!email_.isEmpty()) {
        output.writeString(3, getEmail());
      }
      for (int i = 0; i < phones_.size(); i++) {
        output.writeMessage(4, phones_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (!email_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getEmail());
      }
      for (int i = 0; i < phones_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, phones_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * [START messages]
     * </pre>
     *
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Person, Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        PersonOrBuilder {
      // Construct using com.hypers.www.protocolbufferdemo.AddressBookProtos.Person.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string name = 1;</code>
       */
      public String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <pre>
       * Unique ID number for this person.
       * </pre>
       *
       * <code>int32 id = 2;</code>
       */
      public int getId() {
        return instance.getId();
      }
      /**
       * <pre>
       * Unique ID number for this person.
       * </pre>
       *
       * <code>int32 id = 2;</code>
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <pre>
       * Unique ID number for this person.
       * </pre>
       *
       * <code>int32 id = 2;</code>
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>string email = 3;</code>
       */
      public String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmail(
          String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      /**
       * <code>repeated .Person.PhoneNumber phones = 4;</code>
       */
      public java.util.List<PhoneNumber> getPhonesList() {
        return java.util.Collections.unmodifiableList(
            instance.getPhonesList());
      }
      /**
       * <code>repeated .Person.PhoneNumber phones = 4;</code>
       */
      public int getPhonesCount() {
        return instance.getPhonesCount();
      }/**
       * <code>repeated .Person.PhoneNumber phones = 4;</code>
       */
      public PhoneNumber getPhones(int index) {
        return instance.getPhones(index);
      }
      /**
       * <code>repeated .Person.PhoneNumber phones = 4;</code>
       */
      public Builder setPhones(
          int index, PhoneNumber value) {
        copyOnWrite();
        instance.setPhones(index, value);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phones = 4;</code>
       */
      public Builder setPhones(
          int index, PhoneNumber.Builder builderForValue) {
        copyOnWrite();
        instance.setPhones(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(PhoneNumber value) {
        copyOnWrite();
        instance.addPhones(value);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(
          int index, PhoneNumber value) {
        copyOnWrite();
        instance.addPhones(index, value);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(
          PhoneNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addPhones(builderForValue);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(
          int index, PhoneNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addPhones(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phones = 4;</code>
       */
      public Builder addAllPhones(
          Iterable<? extends PhoneNumber> values) {
        copyOnWrite();
        instance.addAllPhones(values);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phones = 4;</code>
       */
      public Builder clearPhones() {
        copyOnWrite();
        instance.clearPhones();
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phones = 4;</code>
       */
      public Builder removePhones(int index) {
        copyOnWrite();
        instance.removePhones(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Person();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          phones_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Person other = (Person) arg1;
          name_ = visitor.visitString(!name_.isEmpty(), name_,
              !other.name_.isEmpty(), other.name_);
          id_ = visitor.visitInt(id_ != 0, id_,
              other.id_ != 0, other.id_);
          email_ = visitor.visitString(!email_.isEmpty(), email_,
              !other.email_.isEmpty(), other.email_);
          phones_= visitor.visitList(phones_, other.phones_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                case 16: {

                  id_ = input.readInt32();
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  email_ = s;
                  break;
                }
                case 34: {
                  if (!phones_.isModifiable()) {
                    phones_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(phones_);
                  }
                  phones_.add(
                      input.readMessage(PhoneNumber.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Person.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Person)
    private static final Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Person();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Person> PARSER;

    public static com.google.protobuf.Parser<Person> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AddressBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddressBook)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .Person people = 1;</code>
     */
    java.util.List<Person>
        getPeopleList();
    /**
     * <code>repeated .Person people = 1;</code>
     */
    Person getPeople(int index);
    /**
     * <code>repeated .Person people = 1;</code>
     */
    int getPeopleCount();
  }
  /**
   * <pre>
   * Our address book file is just one of these.
   * </pre>
   *
   * Protobuf type {@code AddressBook}
   */
  public  static final class AddressBook extends
      com.google.protobuf.GeneratedMessageLite<
          AddressBook, AddressBook.Builder> implements
      // @@protoc_insertion_point(message_implements:AddressBook)
      AddressBookOrBuilder {
    private AddressBook() {
      people_ = emptyProtobufList();
    }
    public static final int PEOPLE_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<Person> people_;
    /**
     * <code>repeated .Person people = 1;</code>
     */
    public java.util.List<Person> getPeopleList() {
      return people_;
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    public java.util.List<? extends PersonOrBuilder>
        getPeopleOrBuilderList() {
      return people_;
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    public int getPeopleCount() {
      return people_.size();
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    public Person getPeople(int index) {
      return people_.get(index);
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    public PersonOrBuilder getPeopleOrBuilder(
        int index) {
      return people_.get(index);
    }
    private void ensurePeopleIsMutable() {
      if (!people_.isModifiable()) {
        people_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(people_);
       }
    }

    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void setPeople(
        int index, Person value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePeopleIsMutable();
      people_.set(index, value);
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void setPeople(
        int index, Person.Builder builderForValue) {
      ensurePeopleIsMutable();
      people_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void addPeople(Person value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePeopleIsMutable();
      people_.add(value);
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void addPeople(
        int index, Person value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePeopleIsMutable();
      people_.add(index, value);
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void addPeople(
        Person.Builder builderForValue) {
      ensurePeopleIsMutable();
      people_.add(builderForValue.build());
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void addPeople(
        int index, Person.Builder builderForValue) {
      ensurePeopleIsMutable();
      people_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void addAllPeople(
        Iterable<? extends Person> values) {
      ensurePeopleIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, people_);
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void clearPeople() {
      people_ = emptyProtobufList();
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void removePeople(int index) {
      ensurePeopleIsMutable();
      people_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < people_.size(); i++) {
        output.writeMessage(1, people_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < people_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, people_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static AddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static AddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static AddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static AddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static AddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static AddressBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static AddressBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AddressBook prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * Our address book file is just one of these.
     * </pre>
     *
     * Protobuf type {@code AddressBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          AddressBook, Builder> implements
        // @@protoc_insertion_point(builder_implements:AddressBook)
        AddressBookOrBuilder {
      // Construct using com.hypers.www.protocolbufferdemo.AddressBookProtos.AddressBook.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .Person people = 1;</code>
       */
      public java.util.List<Person> getPeopleList() {
        return java.util.Collections.unmodifiableList(
            instance.getPeopleList());
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public int getPeopleCount() {
        return instance.getPeopleCount();
      }/**
       * <code>repeated .Person people = 1;</code>
       */
      public Person getPeople(int index) {
        return instance.getPeople(index);
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder setPeople(
          int index, Person value) {
        copyOnWrite();
        instance.setPeople(index, value);
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder setPeople(
          int index, Person.Builder builderForValue) {
        copyOnWrite();
        instance.setPeople(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder addPeople(Person value) {
        copyOnWrite();
        instance.addPeople(value);
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder addPeople(
          int index, Person value) {
        copyOnWrite();
        instance.addPeople(index, value);
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder addPeople(
          Person.Builder builderForValue) {
        copyOnWrite();
        instance.addPeople(builderForValue);
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder addPeople(
          int index, Person.Builder builderForValue) {
        copyOnWrite();
        instance.addPeople(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder addAllPeople(
          Iterable<? extends Person> values) {
        copyOnWrite();
        instance.addAllPeople(values);
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder clearPeople() {
        copyOnWrite();
        instance.clearPeople();
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder removePeople(int index) {
        copyOnWrite();
        instance.removePeople(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AddressBook)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new AddressBook();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          people_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          AddressBook other = (AddressBook) arg1;
          people_= visitor.visitList(people_, other.people_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!people_.isModifiable()) {
                    people_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(people_);
                  }
                  people_.add(
                      input.readMessage(Person.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (AddressBook.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:AddressBook)
    private static final AddressBook DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AddressBook();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static AddressBook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AddressBook> PARSER;

    public static com.google.protobuf.Parser<AddressBook> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
