// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.hypers.www.protocolbufferdemo;

public final class Addressbook {
    private Addressbook() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public interface SearchRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.hypers.www.protocolbufferdemo.SearchRequest)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional string query = 1;</code>
         */
        String getQuery();

        /**
         * <code>optional string query = 1;</code>
         */
        com.google.protobuf.ByteString
        getQueryBytes();

        /**
         * <code>optional int32 page_number = 2;</code>
         */
        int getPageNumber();

        /**
         * <code>optional int32 result_per_page = 3;</code>
         */
        int getResultPerPage();
    }

    /**
     * Protobuf type {@code com.hypers.www.protocolbufferdemo.SearchRequest}
     */
    public static final class SearchRequest extends
            com.google.protobuf.GeneratedMessageLite<
                    SearchRequest, SearchRequest.Builder> implements
            // @@protoc_insertion_point(message_implements:com.hypers.www.protocolbufferdemo.SearchRequest)
            SearchRequestOrBuilder {
        private SearchRequest() {
            query_ = "";
        }

        public static final int QUERY_FIELD_NUMBER = 1;
        private String query_;

        /**
         * <code>optional string query = 1;</code>
         */
        public String getQuery() {
            return query_;
        }

        /**
         * <code>optional string query = 1;</code>
         */
        public com.google.protobuf.ByteString
        getQueryBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(query_);
        }

        /**
         * <code>optional string query = 1;</code>
         */
        private void setQuery(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            query_ = value;
        }

        /**
         * <code>optional string query = 1;</code>
         */
        private void clearQuery() {

            query_ = getDefaultInstance().getQuery();
        }

        /**
         * <code>optional string query = 1;</code>
         */
        private void setQueryBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            query_ = value.toStringUtf8();
        }

        public static final int PAGE_NUMBER_FIELD_NUMBER = 2;
        private int pageNumber_;

        /**
         * <code>optional int32 page_number = 2;</code>
         */
        public int getPageNumber() {
            return pageNumber_;
        }

        /**
         * <code>optional int32 page_number = 2;</code>
         */
        private void setPageNumber(int value) {

            pageNumber_ = value;
        }

        /**
         * <code>optional int32 page_number = 2;</code>
         */
        private void clearPageNumber() {

            pageNumber_ = 0;
        }

        public static final int RESULT_PER_PAGE_FIELD_NUMBER = 3;
        private int resultPerPage_;

        /**
         * <code>optional int32 result_per_page = 3;</code>
         */
        public int getResultPerPage() {
            return resultPerPage_;
        }

        /**
         * <code>optional int32 result_per_page = 3;</code>
         */
        private void setResultPerPage(int value) {

            resultPerPage_ = value;
        }

        /**
         * <code>optional int32 result_per_page = 3;</code>
         */
        private void clearResultPerPage() {

            resultPerPage_ = 0;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!query_.isEmpty()) {
                output.writeString(1, getQuery());
            }
            if (pageNumber_ != 0) {
                output.writeInt32(2, pageNumber_);
            }
            if (resultPerPage_ != 0) {
                output.writeInt32(3, resultPerPage_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (!query_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(1, getQuery());
            }
            if (pageNumber_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, pageNumber_);
            }
            if (resultPerPage_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, resultPerPage_);
            }
            memoizedSerializedSize = size;
            return size;
        }

        public static SearchRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static SearchRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static SearchRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static SearchRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static SearchRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }

        public static SearchRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static SearchRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }

        public static SearchRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static SearchRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }

        public static SearchRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(SearchRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        /**
         * Protobuf type {@code com.hypers.www.protocolbufferdemo.SearchRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        SearchRequest, Builder> implements
                // @@protoc_insertion_point(builder_implements:com.hypers.www.protocolbufferdemo.SearchRequest)
                SearchRequestOrBuilder {
            // Construct using com.hypers.www.protocolbufferdemo.Addressbook.SearchRequest.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>optional string query = 1;</code>
             */
            public String getQuery() {
                return instance.getQuery();
            }

            /**
             * <code>optional string query = 1;</code>
             */
            public com.google.protobuf.ByteString
            getQueryBytes() {
                return instance.getQueryBytes();
            }

            /**
             * <code>optional string query = 1;</code>
             */
            public Builder setQuery(
                    String value) {
                copyOnWrite();
                instance.setQuery(value);
                return this;
            }

            /**
             * <code>optional string query = 1;</code>
             */
            public Builder clearQuery() {
                copyOnWrite();
                instance.clearQuery();
                return this;
            }

            /**
             * <code>optional string query = 1;</code>
             */
            public Builder setQueryBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setQueryBytes(value);
                return this;
            }

            /**
             * <code>optional int32 page_number = 2;</code>
             */
            public int getPageNumber() {
                return instance.getPageNumber();
            }

            /**
             * <code>optional int32 page_number = 2;</code>
             */
            public Builder setPageNumber(int value) {
                copyOnWrite();
                instance.setPageNumber(value);
                return this;
            }

            /**
             * <code>optional int32 page_number = 2;</code>
             */
            public Builder clearPageNumber() {
                copyOnWrite();
                instance.clearPageNumber();
                return this;
            }

            /**
             * <code>optional int32 result_per_page = 3;</code>
             */
            public int getResultPerPage() {
                return instance.getResultPerPage();
            }

            /**
             * <code>optional int32 result_per_page = 3;</code>
             */
            public Builder setResultPerPage(int value) {
                copyOnWrite();
                instance.setResultPerPage(value);
                return this;
            }

            /**
             * <code>optional int32 result_per_page = 3;</code>
             */
            public Builder clearResultPerPage() {
                copyOnWrite();
                instance.clearResultPerPage();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.hypers.www.protocolbufferdemo.SearchRequest)
        }

        protected final Object dynamicMethod(
                MethodToInvoke method,
                Object arg0, Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new SearchRequest();
                }
                case IS_INITIALIZED: {
                    return DEFAULT_INSTANCE;
                }
                case MAKE_IMMUTABLE: {
                    return null;
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case VISIT: {
                    Visitor visitor = (Visitor) arg0;
                    SearchRequest other = (SearchRequest) arg1;
                    query_ = visitor.visitString(!query_.isEmpty(), query_,
                            !other.query_.isEmpty(), other.query_);
                    pageNumber_ = visitor.visitInt(pageNumber_ != 0, pageNumber_,
                            other.pageNumber_ != 0, other.pageNumber_);
                    resultPerPage_ = visitor.visitInt(resultPerPage_ != 0, resultPerPage_,
                            other.resultPerPage_ != 0, other.resultPerPage_);
                    if (visitor == MergeFromVisitor
                            .INSTANCE) {
                    }
                    return this;
                }
                case MERGE_FROM_STREAM: {
                    com.google.protobuf.CodedInputStream input =
                            (com.google.protobuf.CodedInputStream) arg0;
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                            (com.google.protobuf.ExtensionRegistryLite) arg1;
                    try {
                        boolean done = false;
                        while (!done) {
                            int tag = input.readTag();
                            switch (tag) {
                                case 0:
                                    done = true;
                                    break;
                                default: {
                                    if (!input.skipField(tag)) {
                                        done = true;
                                    }
                                    break;
                                }
                                case 10: {
                                    String s = input.readStringRequireUtf8();

                                    query_ = s;
                                    break;
                                }
                                case 16: {

                                    pageNumber_ = input.readInt32();
                                    break;
                                }
                                case 24: {

                                    resultPerPage_ = input.readInt32();
                                    break;
                                }
                            }
                        }
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw new RuntimeException(e.setUnfinishedMessage(this));
                    } catch (java.io.IOException e) {
                        throw new RuntimeException(
                                new com.google.protobuf.InvalidProtocolBufferException(
                                        e.getMessage()).setUnfinishedMessage(this));
                    } finally {
                    }
                }
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    if (PARSER == null) {
                        synchronized (SearchRequest.class) {
                            if (PARSER == null) {
                                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                            }
                        }
                    }
                    return PARSER;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:com.hypers.www.protocolbufferdemo.SearchRequest)
        private static final SearchRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new SearchRequest();
            DEFAULT_INSTANCE.makeImmutable();
        }

        public static SearchRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<SearchRequest> PARSER;

        public static com.google.protobuf.Parser<SearchRequest> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
